"""Add post views

Revision ID: 27796e3991a1
Revises: 1ac3c75f54c4
Create Date: 2026-09-08 13:55:08.450981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27796e3991a1'
down_revision = '1ac3c75f54c4'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
